# version: 2
# updates:
#   - package-ecosystem: "terraform"
#     directory: "00-bootstrap"
#     schedule:
#       interval: "monthly"
#     commit-message:
#       prefix: "chore(deps): "
#     rebase-strategy: "disabled"
#   - package-ecosystem: "terraform"
#     directory: "03-networks/modules/base_shared_vpc"
#     schedule:
#       interval: "monthly"
#     commit-message:
#       prefix: "chore(deps): "
#     rebase-strategy: "disabled"
#   - package-ecosystem: "terraform"
#     directory: "04-projects/modules/single_project"
#     schedule:
#       interval: "monthly"
#     commit-message:
#       prefix: "chore(deps): "
#     rebase-strategy: "disabled"
#   - package-ecosystem: "terraform"
#     directory: "11-gke-infra/modules/single_cluster"
#     schedule:
#       interval: "monthly"
#     commit-message:
#       prefix: "chore(deps): "
#     rebase-strategy: "disabled"
